---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r libraries, results='hide'}
library(Seurat)
library(ggplot2)
library(patchwork)
library(dplyr)
library(biomaRt)
library(pheatmap)
library(fgsea)
library(patchwork)
library(scales)
library(ggbreak)
library(ggcyto)
library(DESeq2)
library(ggrepel)
library(Matrix)
library(DESeq2)
library(MAST)
options(future.globals.maxSize = 5000 * 1024^2)
setwd("C:/Users/rohit/OneDrive - Loyola University Chicago/Zhang Lab/MDS Project/RNA Seq/GSE263300/")

run_gsea <- function(markers, gmt_path, output_gsea) {
rnk <- setNames(markers$avg_log2FC, rownames(markers))
rnk <- rnk[!is.na(rnk)]
gmt <- gmtPathways(gmt_path)
gsea <- fgsea(pathways = gmt, stats = rnk, minSize = 10, maxSize = 500)
gseadf <- as.data.frame(gsea)
list_columns <- sapply(gseadf, is.list)
gseadf[list_columns] <- lapply(gseadf[list_columns], function(col) sapply(col, paste, collapse = ";"))
write.csv(gseadf, output_gsea)
}

run_gsea_seu <- function(markers, gmt_path, output_gsea) {
rnk <- setNames(markers$avg_log2FC, markers$gene)
rnk <- rnk[!is.na(rnk)]
gmt <- gmtPathways(gmt_path)
gsea <- fgsea(pathways = gmt, stats = rnk, minSize = 10, maxSize = 500)
gseadf <- as.data.frame(gsea)
list_columns <- sapply(gseadf, is.list)
gseadf[list_columns] <- lapply(gseadf[list_columns], function(col) sapply(col, paste, collapse = ";"))
write.csv(gseadf, output_gsea)
}

EnsIDReplace2 <- function(input, output){
  gene_mapping <- read.csv("C:/Users/rohit/OneDrive - Loyola University Chicago/Zhang Lab/RNASeq/Cite-seq/GSE145491/Ensembl_labels.csv")
  rna <- input
  rnanames <- rownames(rna)
  id_list <- setNames(gene_mapping$gene_name, gene_mapping$gene_id)
  rnaname <- character(nrow(rna))
  for (i in seq_len(nrow(rna))) {
    ensembl_id <- rownames(rna)[i]
    if (ensembl_id %in% names(id_list)) {
      rnaname[i] <- id_list[[ensembl_id]]
    } else{
      rnaname[i] <- ensembl_id
    }
  }
  rnaname[rnaname == ""] <- NA
  
  rownames(rna) <- rnaname
  output <- rna
  rm(gene_mapping, id_list, ensembl_id, i, rnaname)
}
```

```{r load data}
expr <- read.csv("expression_matrix.csv", row.names = 1)
cell.meta <- read.csv("cell_metadata.csv", row.names = 1)
so <- CreateSeuratObject(counts = expr, meta.data = cell.meta)
rm(expr, cell.meta)
```

```{r Process SO}
so <- NormalizeData(so)
so <- FindVariableFeatures(so)
so <- ScaleData(so)
so <- RunPCA(so)
so <- FindNeighbors(so, dims = 1:30)
so <- FindClusters(so, resolution = 0.8)
so <- RunUMAP(so, dims = 1:30)
```

seuratobject rdata file has already run through this point

```{r Visualize}
umap <- DimPlot(so, group.by = "seurat_clusters")
ggsave("umap_cluster.png", plot = umap, dpi = 600)

umap_label <- DimPlot(so, group.by = "label")
umap_label
ggsave("umap_label.png", plot = umap_label, dpi = 600)
```

SLAMF1 = CD150
ENG = CD105
TFRC = CD71


```{r Cluster Identification}
deg <- FindAllMarkers(so)
write.csv(deg, "clustermarkers.csv")

hsc_genes <- c("AVP", "HLF", "PROM1")
hspc <- c("CD34", "PROM1")
gmp <- c("MPO", "ELANE", "S100A8", "S100A9")
mep <- c("TFRC", "KLF1", "GATA1")
mk <- c("PF4", "ITGA2B", "GP9")
mast <- c("MITF", "KIT", "KRT1")
eobp <- c("IL3RA", "IL5RA", "FCER1A")
genesets <- list(hsc = hsc_genes,
                 hspc = hspc,
                 gmp = gmp,
                 mep = mep,
                 mk = mk,
                 mast = mast,
                 eobp = eobp)

write.csv(genesets, "celltypelabels.csv")

for (name in names(genesets)) {
  so <- AddModuleScore(so, features = list(genesets[[name]]), name = name)
}

cluster_ids <- levels(so$seurat_clusters)
scores <- sapply(names(genesets), function(name) {
  score_col <- paste0(name, "1")
  tapply(so[[score_col]][,1], so$seurat_clusters, mean)
})
scores <- as.data.frame(scores)
rownames(scores) <- cluster_ids

pheatmap(scores,
         cluster_rows = TRUE,
         cluster_cols = TRUE,
         scale = "row",
         color = colorRampPalette(c("blue", "white", "red"))(100),
         treeheight_row = 0,
         treeheight_col = 0,
         main = "Module Score Heatmap",
         filename = "modulescoreheatmap.png")

so$label <- NA
so$label[so$seurat_clusters %in% c(2, 5, 14)] <- "HSC/HSPC"
so$label[so$seurat_clusters %in% c(12, 3, 10)] <- "MEP/Erythroid"
so$label[so$seurat_clusters %in% c(16, 18)] <- "MEP/MK"
so$label[so$seurat_clusters %in% c(13, 15, 4, 6)] <- "EoBP"
so$label[so$seurat_clusters %in% c(11, 19, 7)] <- "GMP"
so$label[so$seurat_clusters %in% c(8, 17, 1, 0, 9)] <- "Mast"
Idents(so) <- "label"

FeatureScatter(so, feature1 = c("MAP3K7"), feature2 = c("RIPK1")) + 
  scale_x_flowjo_biexp() + 
  scale_y_flowjo_biexp()

# Step 1: create a combined grouping factor
so$group <- paste(so$label, so$dataset, sep = "_")

# Step 2: run pseudobulk expression for MAP3K7
tak1 <- PseudobulkExpression(
  so,
  assay = "RNA",
  group.by = "group",
  features = "MAP3K7"
)

# Step 3: convert to a tidy table with cluster and dataset split out
expr_table <- data.frame(
  cluster = sapply(strsplit(rownames(tak1), "_"), `[`, 1),
  dataset = sapply(strsplit(rownames(tak1), "_"), `[`, 2),
  expression = tak1[, "MAP3K7"]
)
write.csv(tak1, "tak1_expr.csv")
```

```{r subset and recluster erythroid}
ery <- subset(so, so$label == c("MEP/Erythroid"))
ery <- NormalizeData(ery)
ery <- FindVariableFeatures(ery)
ery <- ScaleData(ery)
ery <- RunPCA(ery)
ery <- FindNeighbors(ery, dims = 1:30)
ery <- FindClusters(ery, resolution = 0.8)
ery <- RunUMAP(ery, dims = 1:30)

# 1. Run SCTransform and create a new assay (e.g. "sct")
ery <- SCTransform(
  ery,
  assay = "RNA",         # or whichever assay holds raw counts
  new.assay.name = "sct",
  vars.to.regress = NULL,  # add regressors if needed
  verbose = FALSE
)

# 2. Switch default assay to "sct"
DefaultAssay(ery) <- "sct"

# 3. Fetch normalized expression for your genes
expr_data <- FetchData(ery, vars = c("cluster_dataset", genes))

DimPlot(ery, split.by = "dataset")

Idents(ery) <- "dataset"
erymarkers <- FindMarkers(ery, ident.1 = "SF3B1", ident.2 = "AAVS", logfc.threshold = 0)


hsc <- subset(so, so$label == c("HSC/HSPC"))
hsc <- NormalizeData(hsc)
hsc <- FindVariableFeatures(hsc)
hsc <- ScaleData(hsc)
hsc <- RunPCA(hsc)
hsc <- FindNeighbors(hsc, dims = 1:30)
hsc <- FindClusters(hsc, resolution = 0.8)
hsc <- RunUMAP(hsc, dims = 1:30)

DimPlot(hsc, split.by = "label")

Idents(hsc) <- "dataset"
hscmarkers <- FindMarkers(hsc, ident.1 = "SF3B1", ident.2 = "AAVS", logfc.threshold = 0)

write.csv(erymarkers, "sf3b1_ery_deg.csv")
write.csv(hscmarkers, "sf3b1_hsc_deg.csv")

Idents(ery) <- "seurat_clusters"
ery$splitcluster <- paste(ery$seurat_clusters, ery$dataset, sep = "_")
Idents(ery) <- "splitcluster"
erydeg <- FindAllMarkers(ery)
Idents(hsc) <- "seurat_clusters"
hsc$splitcluster <- paste(hsc$seurat_clusters, hsc$dataset, sep = "_")
Idents(hsc) <- "splitcluster"
hscdeg <- FindAllMarkers(hsc)

write.csv(erydeg, "clustermarker_ery.csv")
write.csv(hscdeg, "clustermarker_hsc.csv")

Idents(ery) <- "seurat_clusters"
erycluster <- FindAllMarkers(ery)
Idents(hsc) <- "seurat_clusters"
hsccluster <- FindAllMarkers(hsc)
```

```{r}
Idents(ery) <- "dataset"
erymarkers <- FindMarkers(ery, ident.1 = "SF3B1", ident.2 = "AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)

Idents(hsc) <- "dataset"
hscmarkers <- FindMarkers(hsc, ident.1 = "SF3B1", ident.2 = "AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)

Idents(so) <- "dataset"
so_sf3b1markers <- FindMarkers(so, ident.1 = "SF3B1", ident.2 = "AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)

Idents(so) <- "group"
hsc_sf3b1 <- FindMarkers(so, ident.1 = "HSC/HSPC_SF3B1", ident.2 = "HSC/HSPC_AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)
ery_sf3b1 <- FindMarkers(so, ident.1 = "MEP/Erythroid_SF3B1", ident.2 = "MEP/Erythroid_AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)
mk_sf3b1 <- FindMarkers(so, ident.1 = "MEP/MK_SF3B1", ident.2 = "MEP/MK_AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)
gmp_sf3b1 <- FindMarkers(so, ident.1 = "GMP_SF3B1", ident.2 = "GMP_AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)
mast_sf3b1 <- FindMarkers(so, ident.1 = "Mast_SF3B1", ident.2 = "Mast_AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)
eobp_sf3b1 <- FindMarkers(so, ident.1 = "EoBP_SF3B1", ident.2 = "EoBP_AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)


```


```{r sf3b1 deg}

# Add -log10 adjusted p-value
so_sf3b1markers$neglog10p <- -log10(so_sf3b1markers$p_val_adj)

# 1. Define your genes of interest in a vector
genes_to_highlight <- c("MAP3K7", "ABCB7", "TMEM14C", "UBA1")

highlight_data <- so_sf3b1markers[rownames(so_sf3b1markers) %in% genes_to_highlight, , drop = FALSE]

sovol <- ggplot(so_sf3b1markers, aes(x = avg_log2FC, y = neglog10p)) +
  geom_point(color = "gray") +
  geom_point(data = highlight_data,
             aes(x = avg_log2FC, y = neglog10p),
             color = "red", size = 3) +
  geom_text_repel(data = highlight_data,
                  aes(x = avg_log2FC, y = neglog10p, 
                      label = rownames(highlight_data)),
                  vjust = -1, color = "red",
                  max.overlaps = Inf) + 
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "blue") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "green") +
  labs(title = "SF3B1 vs AAVS",
       x = "Log2 Fold Change", y = "-Log10 Adjusted P-value") +  
  theme_minimal()
sovol

ggsave("so_volcano.png", plot = sovol, dpi = 600)

# Add -log10 adjusted p-value
ery_sf3b1$neglog10p <- -log10(ery_sf3b1$p_val_adj)

ery_highlight_data <- ery_sf3b1[rownames(ery_sf3b1) %in% genes_to_highlight, , drop = FALSE]

# Volcano plot
eryvol <- ggplot(ery_sf3b1, aes(x = avg_log2FC, y = neglog10p)) +
  geom_point(color = "gray") +
  geom_point(data = ery_highlight_data,
             aes(x = avg_log2FC, y = neglog10p),
             color = "red", size = 3) +
  geom_text_repel(data = ery_highlight_data,
                  aes(x = avg_log2FC, y = neglog10p, 
                      label = rownames(ery_highlight_data)),
                  vjust = -1, color = "red",
                  max.overlaps = Inf) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "blue") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "green") +
  labs(title = "Erythroid SF3B1 vs AAVS",
       x = "Log2 Fold Change", y = "-Log10 Adjusted P-value") + 
  theme_minimal()

eryvol

ggsave("ery_volcano.png", plot = eryvol, dpi = 600)

# Add -log10 adjusted p-value
hsc_sf3b1$neglog10p <- -log10(hsc_sf3b1$p_val_adj)
hsc_highlight_data <- hsc_sf3b1[rownames(hsc_sf3b1) %in% genes_to_highlight, , drop = FALSE]

# Volcano plot
hscvol <- ggplot(hsc_sf3b1, aes(x = avg_log2FC, y = neglog10p)) +
  geom_point(color = "gray") +
  # Use the safe 'hsc_highlight_data' subset
  geom_point(data = hsc_highlight_data,
             aes(x = avg_log2FC, y = neglog10p),
             color = "red", size = 3) +
  # Upgraded from geom_text to geom_text_repel for consistency
  geom_text_repel(data = hsc_highlight_data,
                  aes(x = avg_log2FC, y = neglog10p, 
                      label = rownames(hsc_highlight_data)),
                  vjust = -1, color = "red",
                  max.overlaps = Inf) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "blue") +
  geom_vline(xintercept = c(-1, 1), linetype = "dashed", color = "green") +
  labs(title = "HSC/HSPC SF3B1 vs AAVS",
       x = "Log2 Fold Change", y = "-Log10 Adjusted P-value") + 
  theme_minimal()

hscvol

ggsave("hsc_volcano.png", plot = hscvol, dpi = 600)

```

```{r TAK1 FC}
a <- so_sf3b1markers["MAP3K7", ]
b <- ery_sf3b1["MAP3K7", ]
c <- hsc_sf3b1["MAP3K7", ]
d <- mk_sf3b1["MAP3K7",]
e <- gmp_sf3b1["MAP3K7", ]
f <- mast_sf3b1["MAP3K7", ]
g <- eobp_sf3b1["MAP3K7",]
MAP3K7 <- rbind(a, b, c, d, e, f, g)
rownames(MAP3K7) <- c("CD34+", "MEP/Erythroid", "HSC/HSPC", "MEP/Mk", "GMP", "Mast", "EoBP")

tak1 <- ggplot(MAP3K7, aes(y=2^(avg_log2FC), x=rownames(MAP3K7), fill = -log10(p_val_adj))) + 
  geom_col(width = 0.5, color = "black") + 
  geom_hline(yintercept = 0, color = "black", linewidth = 1) + 
  geom_hline(yintercept = 1, color = "black", linetype = "dashed", linewidth = 1) + 
  theme(
    panel.background = element_rect(fill = "white"), 
    panel.border = element_rect(color = "black", fill = NA), 
    plot.title = element_text(hjust = 0.5), 
    axis.text=element_text(color="black", face="bold")
    ) + 
  scale_y_continuous(limits = c(0, 1.0)) + 
  scale_fill_gradient2(low="blue", mid="white", high="red", midpoint = -log10(0.05) ) + 
  labs(x="Celltype", y="Fold Change", title="Change in TAK1 Expression") 
tak1

ggsave("tak1fc.png", tak1, dpi = 600)

a <- so_sf3b1markers["GATA1", ]
b <- ery_sf3b1["GATA1", ]
c <- hsc_sf3b1["GATA1", ]
d <- mk_sf3b1["GATA1",]
e <- gmp_sf3b1["GATA1", ]
f <- mast_sf3b1["GATA1", ]
g <- eobp_sf3b1["GATA1",]
GATA1 <- rbind(a, b, c, d, e, f, g)
rownames(GATA1) <- c("CD34+", "MEP/Erythroid", "HSC/HSPC", "MEP/Mk", "GMP", "Mast", "EoBP")


gata1 <- ggplot(GATA1, aes(y=2^(avg_log2FC), x=rownames(GATA1), fill = -log10(p_val_adj))) + 
  geom_col(width = 0.5, color = "black") + 
  geom_hline(yintercept = 0, color = "black", linewidth = 1) + 
  geom_hline(yintercept = 1, color = "black", linetype = "dashed", linewidth = 1) + 
  theme(
    panel.background = element_rect(fill = "white"), 
    panel.border = element_rect(color = "black", fill = NA), 
    plot.title = element_text(hjust = 0.5), 
    axis.text=element_text(color="black", face="bold")
    ) + 
  scale_y_continuous(limits = c(0, 1.2)) + 
  scale_fill_gradient2(low="blue", mid="white", high="red", midpoint = 1 , limits = c(0, 25)) + 
  labs(x="Celltype", y="Fold Change", title="Change in GATA1 Expression") 
gata1
```


```{r label erythroid}
erymarker <- read.csv("ErythroidProgenitorMarkers.csv")

genesets <- list(MEP = erymarker$MEP,
                 BFU_E = erymarker$BFU_E,
                 CFU_E = erymarker$CFU_E,
                 ProE = erymarker$ProE)

for (name in names(genesets)) {
  ery <- AddModuleScore(ery, features = list(genesets[[name]]), name = name)
}

cluster_ids <- levels(ery$seurat_clusters)
scores <- sapply(names(genesets), function(name) {
  score_col <- paste0(name, "1")
  tapply(ery[[score_col]][,1], ery$seurat_clusters, mean)
})
scores <- as.data.frame(scores)
rownames(scores) <- cluster_ids

ery_hm <- pheatmap(scores,
         cluster_rows = TRUE,
         cluster_cols = FALSE,
         scale = "column",
         color = colorRampPalette(c("blue", "white", "red"))(100),
         treeheight_row = 0,
         treeheight_col = 0,
         main = "Erythroid Module Score Heatmap")

ery_hm

ggsave("erymodulescore.png", plot = ery_hm, dpi = 600, width = 5, height = 6)

Idents(ery) <- "seurat_clusters"
VlnPlot(ery, features = "MEP1")

ery$erylabel <- NA
ery$erylabel[ery$seurat_clusters %in% c(4, 5, 9, 11)] <- "MEP"
ery$erylabel[ery$seurat_clusters %in% c(0, 2, 10)] <- "BFU_E"
ery$erylabel[ery$seurat_clusters %in% c(6, 7)] <- "CFU_E"
ery$erylabel[ery$seurat_clusters %in% c(1, 3)] <- "ProE"
ery$erylabel[ery$seurat_clusters %in% c(8)] <- "Misc"
Idents(ery) <- "erylabel"
ery$erylabel <- factor(ery$erylabel,
                       levels = c("MEP", "BFU_E", "CFU_E", "ProE", "Misc"))
ery_label <- DimPlot(ery, group.by = "erylabel")
ggsave("erylabelumap.png", plot = ery_label, dpi = 600)

VlnPlot(ery, features = c("MAP3K7"), split.by = "dataset")
```

```{r erythroid tak1}

ery$group2 <- paste(ery$erylabel, ery$dataset, sep = "_")
Idents(ery) <- "group2"
erycluster_sf3b1_markers <- FindAllMarkers(ery, logfc.threshold = 0)
Idents(ery) <- "erylabel"

Idents(ery) <- "group2"
mep_sf3b1 <- FindMarkers(ery, ident.1 = "MEP_SF3B1", ident.2 = "MEP_AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)
bfue_sf3b1 <- FindMarkers(ery, ident.1 = "BFU_E_SF3B1", ident.2 = "BFU_E_AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)
cfue_sf3b1 <- FindMarkers(ery, ident.1 = "CFU_E_SF3B1", ident.2 = "CFU_E_AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)
proe_sf3b1 <- FindMarkers(ery, ident.1 = "ProE_SF3B1", ident.2 = "ProE_AAVS", test.use = "MAST", 
                         latent.vars = c("nCount_RNA", "pct_counts_mt"), logfc.threshold = 0)

m <- mep_sf3b1["MAP3K7", ]
b <- bfue_sf3b1["MAP3K7", ]
c <- cfue_sf3b1["MAP3K7", ]
p <- proe_sf3b1["MAP3K7",]
MAP3K7_ery <- rbind(m, b, c, p)
rownames(MAP3K7_ery) <- c("MEP", "BFU-E", "CFU-E", "ProE")
MAP3K7_ery$celltype <- rownames(MAP3K7_ery)
MAP3K7_ery$celltype <- factor(
  MAP3K7_ery$celltype,
  levels = c("MEP", "BFU-E", "CFU-E", "ProE", "Misc")
)

tak1_ery <- ggplot(MAP3K7_ery, aes(y=2^(avg_log2FC), x=celltype, fill = -log10(p_val_adj))) + 
  geom_col(width = 0.5, color = "black") + 
  geom_hline(yintercept = 0, color = "black", linewidth = 1) + 
  geom_hline(yintercept = 1, color = "black", linetype = "dashed", linewidth = 1) + 
  theme(
    panel.background = element_rect(fill = "white"), 
    panel.border = element_rect(color = "black", fill = NA), 
    plot.title = element_text(hjust = 0.5), 
    axis.text=element_text(color="black", face="bold")
    ) + 
  scale_y_continuous(limits = c(0, 1.2)) + 
  scale_fill_gradient2(low="blue", mid="white", high="red", midpoint = -log10(0.05), limits = c(0, 2) ) + 
  labs(x="Celltype", y="Fold Change", title="Change in TAK1 Expression") 
tak1_ery

ggsave("tak1eryfc.png", tak1_ery, dpi = 600)

Idents(ery) <- "group2"
ery$group2 <- factor(ery$group2, levels = c("MEP_AAVS", "MEP_SF3B1", "BFU_E_AAVS", "BFU_E_SF3B1", "CFU_E_AAVS", "CFU_E_SF3B1", "ProE_AAVS", "ProE_SF3B1", "Misc_AAVS", "Misc_SF3B1"))
VlnPlot(ery, features = c("GATA1"))

m <- mep_sf3b1["GATA1", ]
b <- bfue_sf3b1["GATA1", ]
c <- cfue_sf3b1["GATA1", ]
p <- proe_sf3b1["GATA1",]
GATA1_ery <- rbind(m, b, c, p)
rownames(GATA1_ery) <- c("MEP", "BFU-E", "CFU-E", "ProE")
GATA1_ery$celltype <- rownames(GATA1_ery)
GATA1_ery$celltype <- factor(
  GATA1_ery$celltype,
  levels = c("MEP", "BFU-E", "CFU-E", "ProE", "Misc")
)

gata1_ery <- ggplot(GATA1_ery, aes(y=2^(avg_log2FC), x=celltype, fill = -log10(p_val_adj))) + 
  geom_col(width = 0.5, color = "black") + 
  geom_hline(yintercept = 0, color = "black", linewidth = 1) + 
  geom_hline(yintercept = 1, color = "black", linetype = "dashed", linewidth = 1) + 
  theme(
    panel.background = element_rect(fill = "white"), 
    panel.border = element_rect(color = "black", fill = NA), 
    plot.title = element_text(hjust = 0.5), 
    axis.text=element_text(color="black", face="bold")
    ) + 
  scale_y_continuous(limits = c(0, 1.5)) + 
  scale_fill_gradient2(low="blue", mid="white", high="red", midpoint = -log10(0.05)) + 
  labs(x="Celltype", y="Fold Change", title="Change in GATA1 Expression") 
gata1_ery

ggsave("gata1eryfc.png", gata1_ery, dpi = 600)

```

```{r label erythroid in hspc}
Idents(hsc) <- "seurat_clusters"
hscallmarker <- FindAllMarkers(hsc)


for (name in names(genesets)) {
  hsc <- AddModuleScore(hsc, features = list(genesets[[name]]), name = name)
}

cluster_ids <- levels(hsc$seurat_clusters)
scores <- sapply(names(genesets), function(name) {
  score_col <- paste0(name, "1")
  tapply(hsc[[score_col]][,1], hsc$seurat_clusters, mean)
})
scores <- as.data.frame(scores)
rownames(scores) <- cluster_ids

pheatmap(scores,
         cluster_rows = TRUE,
         cluster_cols = FALSE,
         scale = "column",
         color = colorRampPalette(c("blue", "white", "red"))(100),
         treeheight_row = 0,
         treeheight_col = 0,
         main = "Module Score Heatmap",
         filename = "modulescoreheatmap_hsc2.png")



```


```{r sf3b1 deg}
Idents(ery) <- "dataset"
sf3b1markers <- FindMarkers(ery, ident.1 = "SF3B1", ident.2 = "AAVS")
sf3b1markers <- subset(sf3b1markers, sf3b1markers$p_val_adj < 0.1)
run_gsea(sf3b1markers, "reactome_go_gsea.gmt", "ery_sf3b1_gsea.csv")
write.csv(sf3b1markers, "ery_sf3b1_degs.csv")
```

```{r DEG dot plot}


degplot <- ggplot(tf, aes(x=-log10(FDR.q.val+0.00001), y=reorder(NAME, -log10(FDR.q.val)), fill = NES))
degplot + geom_point(size=5, shape=21) + 
 theme(
    panel.background = element_rect(fill = "white"), 
    panel.border = element_rect(color = "black", fill = NA), 
    plot.title = element_text(hjust = 0.5), 
    axis.text=element_text(color="black", face="bold")
    ) +
  scale_fill_gradient2(low="blue", mid="white", high="red", midpoint=0, limits=c(-2.1,2.1)) + 
  labs(x="-log(FDR q value)", y="Genesets", title="T cell & Lymphoma Genesets") +
  xlim(0,5.1)

```


```{r cleanup}
rm(avg_exp, avg_exp_df, avg_expr, b, c, counts, e, expr_data, expr_table, gsea, gseadf, h, heatmap_df, m, p, pb, s, umap, umap_label, tak1, tak1_ery, sovol, ery_hm, eryvol, gata1, gata1_ery, hscvol, mat, clust_num, cluster_ids, clusters, cond, eobp, genes, genes_to_highlight, gmp, hsc_genes, hspc, labs, list_columns, mast, mep, mk, name, ord, rnk)

rm(so, ery, hsc)
```